version: 2.1
jobs:
  build:
    docker:
      - image: docker:stable
    steps:
      - run:
          command: echo "here goes your build steps"

  tests:
    docker:
      - image: docker:stable
    steps:
      - run:
          command: echo "here goes your tests steps"

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - tests:
          requires:
            - build
